### ISSUE TITLE
동기화 요청에 대한 응답 기능 구현

### ISSUE THREAD

**Issue by na-yk** [PickSa/picksa-sync-server#3]
## 🦁 Describe

픽사 서버에서 동기화 요청을 했을 때 지원서 데이터를 반환하는 기능을 구현합니다.
- 이전 요청 시간이 주어지지 않으면 전체 데이터를 전달합니다.
- 이전 요청 시간이 주어지면 해당 시간 이후에 생성된 데이터를 전달합니다.
- 처리된 기준 시간을 함께 전달합니다.
  - 이후 요청에서 해당 시점 이후에 생성된 데이터만 처리할 수 있습니다.
 
## ✅ Tasks

- [ ] 전체 데이터 반환 서비스 코드 구현
- [ ] 특정 시간 이후에 생성된 데이터 반환 서비스 코드 구현
- [ ] 요청에 이전 요청 시간 유무에 따라 서비스 코드 분기처리
