### ISSUE TITLE
구글폼 응답 결과(csv 파일)를 STARTLION 프로젝트 DB 구조로 변환하는 기능 추가

### ISSUE THREAD

**Issue by na-yk** [PickSa/picksa-sync-server#5]
## 🦁 Describe

구글 폼 응답 결과를 csv 파일로 추출하여 DB에 import하는 것으로 요구 사항이 변경되었습니다. 
다만, 구글 폼 응답 결과를 csv 파일로 추출하면 각 문항 개수만큼 칼럼이 생성되기 때문에, 기존에 작업하던 STARTLION DB 구조와 상이하여 어려움이 있습니다. 따라서 구글 폼 응답 결과를 STARTLION DB 구조로 변환하는 기능이 필요합니다.

#### 변환에서 특히 고려해야 하는 부분
- 파트별 질문에 대한 답변
  - 구글 폼에서는 각 파트별 질문을 모두 합친 개수 만큼 칼럼이 생성됨
  - 이를 각 파트별로 선택 질문은 최대 3개라고 가정하고, `partAnswer1`, `partAnswer2`, `partAnswer3` 칼럼 세 개로 줄임
- 일자별 면접 가능 시간
  - 구글 폼에서는 면접 일정 일자마다 아래와 같은 형식으로 면접 가능 시간이 기록됨
    - `09:00 - 10:00, 11:00 - 12:00, 12:00 - 13:00, 13:00 - 14:00`
    - 이를 기존에 클라이언트와 합의한대로 이진수 형식으로 변환

## ✅ Tasks

- [ ] 구글 폼 응답 결과 파일을 import하는 테이블
  - [ ] 해당 테이블을 다룰 수 있는 클래스 추가(`OriginalApplication`)
- [ ] `OriginalApplication`을 `Application`으로 변환하는 기능 구현
  - [ ] `OriginalApplication`에서는 각 파트별로 답변이 기록되는 칼럼이 다르므로 `Converter`를 따로 구현
- [ ] 변환된 `Application`을 데이터베이스에 저장하는 기능 구현
